name: Referrals service commands CI/CD pipeline for sandbox environment.


on:
  push:
    branches: [ "feature/*" ]

  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'

jobs:

  build-ReferralsServiceCommands-sandbox:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/MessageLambda
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore project dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --no-restore 
      
      - name: Test project
        run: dotnet test --no-build --verbosity normal
          
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
