name: Referrals service commands CI/CD pipeline for dev environment.


on:
  push:
    branches: [ test ]

  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x
  PUBLISH_DIR: ./bin/Release/net6.0/publish
  PUBLISH_FRAMEWORK: net6.0
  ENVIRONMENT_NAME: test
  PROJECT_NAME: ReferralsServiceCommands
  AWS_S3_BUCKET: referrals-service-commands-test
  AWS_STACKNAME: ReferralsServiceCommands-test
  CFN_TEMPLATE: ./cloudformation/referrals-service-commands-message-cfn.yaml
  
jobs:

  build-ReferralsServiceCommands-test:
    runs-on: ubuntu-latest

    environment: test

    defaults:
      run:
        working-directory: ./src/MessageLambda

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore project dependencies
        run: dotnet restore
      
      - name: Build project
        run: dotnet build --no-restore 
      
      - name: Test project
        run: dotnet test --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish --output ${{env.PUBLISH_DIR}} --configuration Release --framework ${{env.PUBLISH_FRAMEWORK}} /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output 
        run: zip -qq -r ${{env.PUBLISH_DIR}}/${{env.PROJECT_NAME}}-${{env.ENVIRONMENT_NAME}}-${{github.run_number}}.zip ${{env.PUBLISH_DIR}}

      - name: Configure AWS credentials from test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.TEST_AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.TEST_AWS_SECRET_KEY}}
          aws-session-token: ${{secrets.TEST_AWS_SESSION_TOKEN}}
          aws-region: ap-southeast-2
      
      - name: Copy files to the AWS S3 bucket with the AWS CLI
        run: aws s3 cp ${{env.PUBLISH_DIR}}/${{env.PROJECT_NAME}}-${{env.ENVIRONMENT_NAME}}-${{github.run_number}}.zip s3://${{env.AWS_S3_BUCKET}}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{env.AWS_STACKNAME}}
          template: ${{env.CFN_TEMPLATE}}
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            ProjectName=${{env.PROJECT_NAME}},
            Environment=${{env.ENVIRONMENT_NAME}},
            BucketName=${{env.AWS_S3_BUCKET}},
            CodeKey=${{env.PROJECT_NAME}}-${{env.ENVIRONMENT_NAME}}-${{github.run_number}}.zip,
            ParamStoreKMSMasterKeyIdARN=/${{env.PROJECT_NAME}}/${{env.ENVIRONMENT_NAME}}/CloudFormation/KMS-Master-KeyIdARN,
            ParamStoreLambdaSecurityGroupIds=/${{env.PROJECT_NAME}}/${{env.ENVIRONMENT_NAME}}/CloudFormation/Lambda-Security-GroupIds,
            ParamStoreLambdaSubnetIds=/${{env.PROJECT_NAME}}/${{env.ENVIRONMENT_NAME}}/CloudFormation/Lambda-SubnetIds
          capabilities: "CAPABILITY_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND"
          role-arn: ${{secrets.TEST_AWS_CFN_EXECUTION_ROLE}}